docs(cn)：翻译风格指南章节
denocn/deno_docs pull request #10
Opened 2021-02-10 15:00 UTC by Kyya

2021-02-10 15:01 UTC, Kyya commented
@justjavac 
@QC-L

2021-02-10 16:41 UTC, justjavac requested changes

2021-02-10 16:41 UTC, justjavac commented on contributing/style_guide.md
> +## 在文件名中使用下划线而非破折号 {#use-underscores-not-dashes-in-filenames}
破折号 --> 连字符

2021-02-10 16:41 UTC, justjavac commented on contributing/style_guide.md
> +### 导出函数：最多 2 个参数，把其余的参数放入一个配置对象中{#exported-functions-max-2-args-put-the-rest-into-an-options-object}
```suggestion
### 导出函数：最多 2 个参数，把其余的参数放入一个配置对象中 {#exported-functions-max-2-args-put-the-rest-into-an-options-object}
```

2021-02-10 16:41 UTC, justjavac commented on contributing/style_guide.md
> +1. 组成公共 API 的函数拥有 0-2 个必选参数，和（如果必要）一个选项对象（总共最多 3 个）。
```suggestion
1. 组成公共 API 的函数拥有 0-2 个必选参数，和（如果必要）一个可选对象（总共最多 3 个）。
```

下同

2021-02-10 16:41 UTC, justjavac commented on contributing/style_guide.md
> +   - 可辨识原型 (e.g. `Array`, `Map`, `Date`, `class MyThing`).
```suggestion
   - 可辨识原型（例如：`Array`、`Map`、`Date`、`class MyThing`）。
```

2021-02-10 16:41 UTC, justjavac commented on contributing/style_guide.md
> +每当使用导出成员的参数中包含的接口时，都应该导出使用的接口。下面是一个例子。
没看明白这句汉语的意思

2021-02-10 16:41 UTC, justjavac commented on contributing/style_guide.md
> +不要记录函数的参数除非他们的目的不是很明确。(虽然目的不明确，但总之 API 应纳入考虑)。因此一般不要使用 `@param`。如果要用，它不应当包含 `类型` 因为 TypeScript 已经在这方面做的很好了。
“(虽然目的不明确，但总之 API 应纳入考虑)” 重新翻译一下

2021-02-13 12:33 UTC, QC-L commented on contributing/style_guide.md
> +## 在文件名中使用下划线而非破折号 {#use-underscores-not-dashes-in-filenames}
```suggestion
## 在文件名中使用下划线而非连字符 {#use-underscores-not-dashes-in-filenames}
```

2021-02-14 13:03 UTC, Kyya commented on contributing/style_guide.md
> +2. 可选参数一般应放入选项对象中。
```suggestion
2. 可选参数一般应放入可选对象中。
```

2021-02-14 13:03 UTC, Kyya commented on contributing/style_guide.md
> +   仅有一个不在选项对象中的可选参数是可接受的，并且未来不考虑新增可选参数。
```suggestion
   仅有一个不在可选对象中的可选参数是可接受的，并且未来不考虑新增可选参数。
```

2021-02-14 13:03 UTC, Kyya commented on contributing/style_guide.md
> +3. 选项参数是唯一的参数且是一个常规的对象。
```suggestion
3. 可选参数是唯一的参数且是一个常规的对象。
```

2021-02-14 13:03 UTC, Kyya commented on contributing/style_guide.md
> +// BAD: 可选参数不是配置对象的一部分 (#2)
```suggestion
// BAD: 可选参数不是可选对象的一部分 (#2)
```

2021-02-14 13:03 UTC, Kyya commented on contributing/style_guide.md
> +// BAD: `env` 可以是一个常规的对象因此不能与选项区分开来。 (#3)
```suggestion
// BAD: `env` 可以是一个常规的对象因此不能与可选对象区分开来。 (#3)
```

2021-02-14 13:25 UTC, Kyya commented on contributing/style_guide.md
> +每当使用导出成员的参数中包含的接口时，都应该导出使用的接口。下面是一个例子。
```suggestion
请一并导出被导出成员所依赖的接口。下面是一个例子。
```

2021-02-14 13:25 UTC, Kyya commented on contributing/style_guide.md
> +不要记录函数的参数除非他们的目的不是很明确。(虽然目的不明确，但总之 API 应纳入考虑)。因此一般不要使用 `@param`。如果要用，它不应当包含 `类型` 因为 TypeScript 已经在这方面做的很好了。
```suggestion
不要为显而易见的函数参数作注释。（虽然它是显而易见的，但总之应以 API 为准）。因此一般不要使用 `@param`。如果一定要用，它不应当包含 `类型` 因为 TypeScript 已经在这方面做的很好了。

```

2021-02-14 13:25 UTC, Kyya commented on contributing/style_guide.md
> + * 无明显参数的函数
```suggestion
 * 函数参数并非显而易见
```

2021-02-14 13:25 UTC, Kyya commented on contributing/style_guide.md
> +/** 这是一个提倡的单行 JSDoc. */
```suggestion
/** 这是一个被提倡的单行 JSDoc 注释 */
```

2021-02-14 13:25 UTC, Kyya commented on contributing/style_guide.md
> + * 这是一个不被提倡的单行 JSDoc.
```suggestion
 * 这是一个不被提倡的单行 JSDoc 注释
```

2021-02-14 13:27 UTC, Kyya commented on contributing/style_guide.md
> +每当使用导出成员的参数中包含的接口时，都应该导出使用的接口。下面是一个例子。
我的理解是：如果一个接口被导出成员所依赖，那么这个接口也应当被导出。

2021-02-14 13:28 UTC, Kyya commented on contributing/style_guide.md
> +不要记录函数的参数除非他们的目的不是很明确。(虽然目的不明确，但总之 API 应纳入考虑)。因此一般不要使用 `@param`。如果要用，它不应当包含 `类型` 因为 TypeScript 已经在这方面做的很好了。
Changed to `不要为显而易见的函数参数作注释。（虽然它是显而易见的，但总之应以 API 为准）。`

2021-02-18 01:14 UTC, QC-L commented on contributing/style_guide.md
> +如果代码来源于其他地方，请确保文件有恰当的版权声明。我们只允许 MIT、BSD 和 Apache 授权的代码。
```suggestion
如果引用了其他地方的代码，请确保文件有恰当的版权声明。我们只允许使用遵循 MIT、BSD 和 Apache 协议的代码。
```

2021-02-18 01:15 UTC, QC-L commented on contributing/style_guide.md
> +## 在文件名中使用下划线而非连字符 {#use-underscores-not-dashes-in-filenames}
```suggestion
## 文件命名请使用下划线，而非连字符 {#use-underscores-not-dashes-in-filenames}
```

2021-02-18 01:16 UTC, QC-L commented on contributing/style_guide.md
> +Deno 不会特殊对待 "index.js" 或 "index.ts"。虽然要使用这些文件名，但又不能将它们排除在模块说明符之外，这十分令人困惑。
多删了空行，与原文不一致了

2021-02-18 01:16 UTC, QC-L commented on contributing/style_guide.md
> +Deno 不会特殊对待 "index.js" 或 "index.ts"。虽然要使用这些文件名，但又不能将它们排除在模块说明符之外，这十分令人困惑。
```suggestion

Deno 不会特殊对待 "index.js" 或 "index.ts"。虽然要使用这些文件名，但又不能将它们排除在模块说明符之外，这十分令人困惑。
```

2021-02-18 01:18 UTC, QC-L commented on contributing/style_guide.md
> +Deno 不会特殊对待 "index.js" 或 "index.ts"。虽然要使用这些文件名，但又不能将它们排除在模块说明符之外，这十分令人困惑。
```suggestion
Deno 不会对 "index.js" 或 "index.ts" 进行特殊处理。虽然要使用这些文件名，但又不能将它们排除在模块说明符之外，这令人十分困惑。
```

2021-02-18 01:20 UTC, QC-L commented on contributing/style_guide.md
> +文档易读性是重要的，但也需要提供额外的样式信息，以确保生成的文档是更丰富的文本。因此 JSDoc 一般应遵循 markdown 标记来丰富文本。
这里也是，多删了空行

2021-02-18 01:20 UTC, QC-L commented on contributing/style_guide.md
> +范例代码不应使用三个反引号 (\`\`\`) 来表示。它们仅应由缩进来标记，在代码块之前需要一个空行，且每行代码前应有 6 个额外的空格。这相比于与第一列的注释缩进了 4 个空格。举例：
这里同上

2021-02-18 02:13 UTC, QC-L approved these changes

2021-02-18 02:14 UTC, merged