docs(cn): 翻译环境配置章节
denocn/deno_docs pull request #9
Opened 2021-02-09 06:44 UTC by ajaxjiang96

2021-02-09 06:44 UTC, ajaxjiang96 commented
@justjavac 
@QC-L

2021-02-09 13:44 UTC, QC-L requested changes

2021-02-09 13:44 UTC, QC-L commented on getting_started/setup_your_environment.md
> +## 配置您的环境 {#set-up-your-environment}
文档不用您，通篇修改下。

2021-02-09 13:44 UTC, QC-L commented on getting_started/setup_your_environment.md
> +范例（bash）：
```suggestion
示例（bash）：
```

2021-02-09 13:44 UTC, QC-L commented on getting_started/setup_your_environment.md
> +范例（不带任何框架的 zsh）：
```suggestion
示例（不带任何框架的 zsh）：
```

2021-02-09 13:44 UTC, QC-L commented on getting_started/setup_your_environment.md
> +范例（不带任何框架的 zsh）：
后面都统一成 示例

2021-02-09 13:44 UTC, QC-L commented on getting_started/setup_your_environment.md
> +最后重启你的终端。请注意，如果自动补全未能成功载入，您可能需要先运行`rm ~/.zcompdump/` 来删除之前创建的补全，再运行`compinit` 来重新生成。
```suggestion
最后重启终端。请注意，如果自动补全未能成功载入，你可能需要先运行 `rm ~/.zcompdump/` 来删除之前生成的 compinit 文件，再运行 `compinit` 来重新生成。
```

2021-02-09 13:44 UTC, QC-L commented on getting_started/setup_your_environment.md
> +随后，将 deno 插件添加到 `~/.zshrc` 文件的 "plugins" 标签下。对于`antigen`之类的工具，你的 path 将会是 `~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins`，而你的指令则是 `antigen bundle deno`，以此类推。
```suggestion
随后，将 deno 插件添加到 `~/.zshrc` 文件的 "plugins" 标签下。对于 `antigen` 之类的工具来说，你的 path 将会是 `~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins`，而你的指令则是 `antigen bundle deno`，以此类推。
```

2021-02-09 13:44 UTC, QC-L commented on getting_started/setup_your_environment.md
> +以上命令默认将会在`$HOME\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1`创建一个 Powershell 的档案，并且会在您每次运行 Powershell 时执行。
```suggestion
以上命令默认会在 `$HOME\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1` 创建一个 Powershell 的配置文件，并且会在你每次运行 Powershell 时执行。
```

2021-02-09 13:44 UTC, QC-L commented on getting_started/setup_your_environment.md
> +### 编辑器和 IDE {#editors-and-ides}
```suggestion
### 编辑器及 IDE {#editors-and-ides}
```

2021-02-09 13:44 UTC, QC-L commented on getting_started/setup_your_environment.md
> +您需要正确地配置环境以高效地使用 Deno 进行开发。配置内容将会涵盖 shell 自动补全，环境变量以及您的 IDE 配置。
这里的您，都改掉

2021-02-09 13:44 UTC, QC-L commented on getting_started/setup_your_environment.md
> +`NO_COLOR` 如果给这个变量赋值，Deno 的输出将不会带有颜色。详情参照 <https://no-color.org/>。 您不需要使用`--allow-env`来验证是否已给`NO_COLOR`赋值，只需要检查 Boolean 常量`Deno.noColor`的值。
```suggestion
如果设置了 `NO_COLOR` 变量，Deno 的输出将不会带有颜色。详情请参照 https://no-color.org/。你不需要使用 `--allow-env` 来验证是否设置了 `NO_COLOR`，只需要检查常量 `Deno.noColor` 的值，其类型为 Boolean。
```

2021-02-09 13:44 UTC, QC-L commented on getting_started/setup_your_environment.md
> +您可以通过`deno completions <shell>`命令来为您的 Shell 生成自动补全脚本并输出到控制台。您仍需要将控制台的输出保存在相关的文件中以使其生效。
```suggestion
你可以通过 `deno completions <shell>` 命令来为你的 Shell 生成自动补全脚本并输出到控制台。你仍需要将控制台的输出保存在相关的文件中以使其生效。
```

2021-02-09 13:44 UTC, QC-L commented on getting_started/setup_your_environment.md
> +Deno 的模组引入机制依赖文件拓展名，并且支持通过 http 导入。由于绝大多数编辑器和编程语言服务器并不对此提供原生支持，很多编辑器在现阶段会由于无法找到文件而报错，或者会在引入时加入不必要的文件拓展名。
```suggestion
由于 Deno 的模块引入机制依赖文件拓展名，且允许通过 http 引入。而目前绝大多数编辑器和语言服务器并未对此提供原生支持，因此很多编辑器在现阶段会因为无法找到文件而报错，或者会在引入时加入不必要的文件拓展名。
```

2021-02-09 13:44 UTC, QC-L commented on getting_started/setup_your_environment.md
> +为了应对这种情况，我们的开发者社区提供了以下编辑器插件：
```suggestion
为了应对这种情况，社区提供了以下编辑器插件：
```

2021-02-09 13:44 UTC, QC-L commented on getting_started/setup_your_environment.md
> +[vscode_deno](https://github.com/denoland/vscode_deno)的测试版已在
```suggestion
[vscode_deno](https://github.com/denoland/vscode_deno) 的测试版已在
```

2021-02-09 13:44 UTC, QC-L commented on getting_started/setup_your_environment.md
> +[Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno)发布，欢迎反馈任何使用中遇到的问题。
请与 75 行合并，请注意文档格式规范

2021-02-09 13:44 UTC, QC-L commented on getting_started/setup_your_environment.md
> +该插件的详细使用说明已发布在 YouTrack 的
```suggestion
此插件的详细使用说明已发布在 YouTrack 的
```

2021-02-09 13:44 UTC, QC-L commented on getting_started/setup_your_environment.md
> +[这条评论](https://youtrack.jetbrains.com/issue/WEB-41607#focus=streamItem-27-4160152.0-0)
```suggestion
[评论](https://youtrack.jetbrains.com/issue/WEB-41607#focus=streamItem-27-4160152.0-0) 中
```

2021-02-09 13:44 UTC, QC-L commented on getting_started/setup_your_environment.md
> +里。
和上面一样，合并成一行。

2021-02-09 13:44 UTC, QC-L commented on getting_started/setup_your_environment.md
> +在安装 CoC 以后，请在 Vim 内运行`:CocInstall coc-tsserver` 和 `:CocInstall coc-deno`。运行`:CocCommand deno.types`以获得对 Deno 类型的自动补选。您也可以选择性地运行`:CocRestart`来重启 CoC 服务器。到此为止， `gd` (跳转到定义) 和 `gr` (跳转到引用)等功能应该已生效。
```suggestion
在安装 CoC 以后，请在 Vim 内运行 `:CocInstall coc-tsserver` 和 `:CocInstall coc-deno`。运行 `:CocCommand deno.types` 以获得对 Deno 类型的自动补选。您也可以选择性地运行 `:CocRestart` 来重启 CoC 服务器。到此为止，`gd` (跳转到定义) 和 `gr` (跳转到引用)等功能应该已生效。
```

2021-02-09 13:44 UTC, QC-L commented on getting_started/setup_your_environment.md
> +ALE 原生支持 Deno 的 LSP（语言服务器协议），不许要额外配置。然而，如果您的 Deno 可执行文件不存在于`$PATH`，或者拥有不同于`deno`的名字，亦或是您想尝试不稳定的特性与接口，您需要覆盖 ALE 的默认值。详情请见 [`:help ale-typescript`](https://github.com/dense-analysis/ale/blob/master/doc
```suggestion
ALE 原生支持 Deno 的 LSP（语言服务器协议），不许要额外配置。然而，如果你的 Deno 可执行文件不存在于 `$PATH`，或者拥有不同于 `deno` 的名字，亦或是你想尝试不稳定的特性与接口，你需要覆盖 ALE 的默认值。详情请见 [`:help ale-typescript`](https://github.com/dense-analysis/ale/blob/master/doc/ale-typescript.txt)。
```

2021-02-09 13:44 UTC, QC-L commented on getting_started/setup_your_environment.md
> +ALE 可以通过运行`deno fmt`来修复 linter 提出的问题。如果想要让 ALE 使用 Deno 的格式化工具，您需要配置 `ale_linter` 。如果您想调整当前 buffer 配置，则使用(`let b:ale_linter = ['deno']`) 。如果想为所有 TypeScript 文件提供全局配置，则需要设置成(`let g:ale_fixers={'typescri
```suggestion
ALE 可以通过运行 `deno fmt` 来修复 linter 提出的问题。如果想要让 ALE 使用 Deno 的格式化工具，您需要配置 `ale_linter`。如果您想调整当前 buffer 配置，则使用（`let b:ale_linter = ['deno']`）。如果想为所有 TypeScript 文件提供全局配置，则需要设置成（`let g:ale_fixers={'typescript': ['deno']}`）。
```

2021-02-09 13:44 UTC, QC-L commented on getting_started/setup_your_environment.md
> +" 通过 Vim 的 'omnifunc' 设置来使用 ALE 的自动补全 (在插入模式下按 <C-x><C-o>)
这段代码块里的暂时不翻译了，看着很奇怪

2021-02-09 13:44 UTC, QC-L commented on getting_started/setup_your_environment.md
> +首先，确保 `tide` 已经在您的 Emacs 实例中正确配置。其次，根据 [typescript-deno-plugin](https://github.com/justjavac/typescript-deno-plugin) 的引导，在您的项目文件夹内运行 `npm install --save-dev typescript-deno-plugin typescript`（如果您仍未初始
通篇检查下，有些描述相关的小括号，未改成中文的括号

2021-02-09 13:49 UTC, ajaxjiang96 commented on getting_started/setup_your_environment.md
> +ALE 可以通过运行`deno fmt`来修复 linter 提出的问题。如果想要让 ALE 使用 Deno 的格式化工具，您需要配置 `ale_linter` 。如果您想调整当前 buffer 配置，则使用(`let b:ale_linter = ['deno']`) 。如果想为所有 TypeScript 文件提供全局配置，则需要设置成(`let g:ale_fixers={'typescri
感觉这里的括号有点奇怪 需要去掉吗？

2021-02-10 01:27 UTC, QC-L commented on getting_started/setup_your_environment.md
> +`DENO_DIR` 的默认值为 `$HOME/.cache/deno`， 但是你可以选择其他任何路径来读写生成的源码。
```suggestion
`DENO_DIR` 的默认值为 `$HOME/.cache/deno`，但是你可以选择其他任何路径来读写生成的源码。
```

2021-02-10 01:29 UTC, QC-L commented on getting_started/setup_your_environment.md
> +该功能支持以下 Shell：
```suggestion
该功能支持以下 shell 环境：
```

2021-02-10 01:38 UTC, QC-L commented on getting_started/setup_your_environment.md
> +以上命令默认将会在`$HOME\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1`创建一个 Powershell 的档案，并且会在你每次运行 Powershell 时执行。
这里没改

2021-02-10 02:02 UTC, ajaxjiang96 commented on getting_started/setup_your_environment.md
> +您需要正确地配置环境以高效地使用 Deno 进行开发。配置内容将会涵盖 shell 自动补全，环境变量以及您的 IDE 配置。
已通篇替换

2021-02-10 06:26 UTC, QC-L commented on getting_started/setup_your_environment.md
> +let g:ale_fix_on_save = 1 " 在保存buffer时运行deno fmt
这里没改掉

2021-02-10 06:28 UTC, QC-L commented on getting_started/setup_your_environment.md
> +        "command": ["deno", "lsp"],
不要改变源代码格式

2021-02-10 07:28 UTC, ajaxjiang96 commented on getting_started/setup_your_environment.md
> +let g:ale_fix_on_save = 1 " 在保存buffer时运行deno fmt
已修改

2021-02-10 07:28 UTC, ajaxjiang96 commented on getting_started/setup_your_environment.md
> +        "command": ["deno", "lsp"],
已修改

2021-02-10 09:17 UTC, QC-L commented on getting_started/setup_your_environment.md
> +如果你未能在以上列表内找到你最爱的 IDE，或许你可以亲自开发扩展程序。我们的[社区 Discord 小组](https://discord.gg/deno) 可以给你提供上手指导。
```suggestion
如果你未能在以上列表内找到你最爱的 IDE，或许你可以亲自开发扩展程序。我们的[社区 Discord 小组](https://discord.gg/deno)可以给你提供上手指导。
```

2021-02-10 09:37 UTC, QC-L approved these changes

2021-02-10 09:38 UTC, merged